Spree::Core::Engine.load_seed if defined?(Spree::Core)
Spree::Auth::Engine.load_seed if defined?(Spree::Auth)
user = User.create(email: "spree@example.com", password: "spree123")
user.spree_roles << Spree::Role.find_or_create_by(name: "admin")
Spree::Taxonomy.create(name: "Categories")
Spree::Taxonomy.create(name: "Brands")
Spree::Taxon.create(name: "Categories", permalink: "categories", taxonomy_id: 1)
Spree::Taxon.create(name: "Brands", permalink: "brands", taxonomy_id: 2)
